### ISSUE TITLE
Inconsistency between legacy (api.adoptopenjdk.net) and new (api.adoptium.net) APIs

### ISSUE THREAD

**Issue by tushev** [adoptium/api.adoptium.net#1014]
Hello,

There's an inconsistency between https://api.adoptopenjdk.net/v3/assets/latest/8/hotspot?architecture=x64&image_type=jre&os=windows&vendor=adoptopenjdk and https://api.adoptium.net/v3/assets/latest/8/hotspot?architecture=x64&image_type=jre&os=windows&vendor=eclipse : the former reports `8.0.402+6` while the latter reports `8.0.412+8`. 

Is this expected?

<hr>

_Reported via https://github.com/tushev/aojdk-updatewatcher/issues/75_

**Comment by tellison** [comment]
Hello @tushev . The old "adoptopenjdk.net" API has been deprecated for over three years now, and should not be used to retrieve latest builds from Adoptium.

We won't be looking into any bugs reported against api.adoptopenjdk.net

**Comment by tushev** [comment]
@tellison thank you for your reply! Perhaps I should finally plan a switch xD

Do you, by chance, know about OpenJ9/Semeru builds - are they still [supported](https://api.adoptopenjdk.net/migration.html) on `api.adotopenjdk.net`?

**Comment by AdamBrousseau** [comment]
Unfortunately IBM has not provided an API equivalent as of yet. Semeru releases are still pushed to AdoptOpenJDK (as well as IBMRuntimes) on Github. So the AdoptOpenJDK api is still serving the latest Semeru releases.
