### ISSUE TITLE
Wrong API URL https://api.adoptium.net/v3/info/available/releases

### ISSUE THREAD

**Issue by AndreVirtimo** [adoptium/api.adoptium.net#1025]
**Describe the bug**
I have tried out some examples from the cookbook. But I ran into 404.

The URL https://api.adoptium.net/v3/info/available/releases has to be https://api.adoptium.net/v3/info/available_releases

See also https://api.adoptium.net/q/swagger-ui/#/Release%20Info/getAvailableReleases

**To Reproduce**
1. run `curl -s https://api.adoptium.net/v3/info/available/releases` like it is mentioned in https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-one-explore-available-releases

**Comment by johnoliver** [comment]
This was temporary as we had not yet deployed the change, it has now been changed, let us know if there are any other issues
