### ISSUE TITLE
Cannot access API via browser or Postman

### ISSUE THREAD

**Issue by dreis2211** [adoptium/api.adoptium.net#119]
Hi,

I'm currently trying to switch from AdoptOpenJDK to Adoptium because the JDK 17 builds from AdoptOpenJDK are not up-to-date.

While checking I noticed that [https://api.adoptium.net/v3/assets/feature_releases/17/ea](https://api.adoptium.net/v3/assets/feature_releases/17/ea?heap_size=normal&image_type=jdk&jvm_impl=hotspot&os=linux&page=0&page_size=10&project=jdk&sort_method=DEFAULT&sort_order=DESC&vendor=adoptium) or any other version is not accessible via Browser or Postman. For some reasons `curl` works, though.

This is e.g. used in Spring-Boot - see https://github.com/spring-projects/spring-boot/blob/main/ci/scripts/detect-jdk-updates.sh#L12 so it would be nice if this is fixed so we can switch there.

Cheers,
Christoph

**Comment by johnoliver** [comment]
that seems to work, is it still failing for you? What error do you see?

**Comment by dreis2211** [comment]
Hmm - now it works. Did you do anything or are you aware if the url was down today? Feel free to close this issue then.
