### ISSUE TITLE
Unexpected behavior of ETag

### ISSUE THREAD

**Issue by Kale-Ko** [adoptium/api.adoptium.net#1276]
**Describe the bug**
When fetching different resources the same ETag is always returned even for wildly different content. This can lead to unexpected behavior of caches but in this case it combines with a Docker buildx bug to produce an issue, see [docker/buildx#2803](https://github.com/docker/buildx/issues/2803). It is also strange behavior that the ETag is returned for some resources only if the Content-Encoding is set to gzip.

**To Reproduce**
1. Run `curl -X GET "https://api.adoptium.net/v3/assets/latest/8/hotspot" -H "Accept-Encoding: gzip" -o /dev/null -v` and observe the ETag
2. Run `curl -X GET "https://api.adoptium.net/v3/info/available_releases" -H "Accept-Encoding: gzip" -o /dev/null -v` and observe the ETag is the same

**Expected behavior**
The ETag is different for different content, generally a hash of the content.

**Device (please complete the following information):**
 - OS: Linux
 - Browser: curl
 - Version 8.11.0

**Comment by johnoliver** [comment]
should be fixed
