### ISSUE TITLE
docker-compose up will not work

### ISSUE THREAD

**Issue by bmarwell** [adoptium/api.adoptium.net#129]
**Describe the bug**

`docker-compose up` will run into missing dependencies

**To Reproduce**
1. Clone repo
2. `docker-compose up`

**Expected behavior**

Docker containers will come up.

**Screenshots**

n/a

**Device (please complete the following information):**
 - OS: Linux
 - Version current main

**Additional context**

Workaround: Will build fine using `mvnw clean install` in `Dockerfile`, which is a code smell.

**Comment by karianna** [comment]
This has been resolved.  You do need to pass in GITHUB_TOKEN and APP_INSIGHTS instrumentation key.
