### ISSUE TITLE
API intermittently fails to pickup new builds

### ISSUE THREAD

**Issue by karianna** [adoptium/api.adoptium.net#148]
**Describe the bug**
When new binaries get released to our GitHub temurinX-binaries repositories the API doesn't always pick them up and an administrator is forced to 'restart' or kick the API (that process is not documented).

**Comment by sxa** [comment]
(Raised as part of the [July 2021 retrospective](https://github.com/adoptium/adoptium/issues/48)

**Comment by karianna** [comment]
@johnoliver Your new endpoint solves this correct?
