### ISSUE TITLE
(Possible) Missing binaries

### ISSUE THREAD

**Issue by funilrys** [adoptium/api.adoptium.net#155]
Hello, 
I was playing with both the `api.adoptopenjdk.net` and `api.adoptium.net` and there is a strange behavior that I can't explain.

I thought that by saying "Good-bye AdoptOpenJDK Hello Adoptium!" that will mean that there won't be any binary loss or API degradation but it doesn't seem to be true. Can someone please explain to me what am I missing here ?

**To Reproduce**

Try to fetch the header from `api.adoptopenjdk.net`:

```
$ curl -IX 'GET'   'https://api.adoptopenjdk.net/v3/assets/feature_releases/11/ga?architecture=x86&heap_size=normal&image_type=jre&jvm_impl=hotspot&os=windows&page=0&page_size=10&project=jdk&sort_method=DEFAULT&sort_order=DESC&vendor=adoptopenjdk'   -H 'accept: application/json'

HTTP/2 200
date: Wed, 08 Sep 2021 09:40:28 GMT
content-type: application/json
set-cookie: b7b892882bae631693e1ea44963ef628=f5366a02d77f28e4d00cf7de250eefda; path=/; HttpOnly; Secure
cache-control: private
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 68b7372aec634a80-FRA
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400
```

As we can see ; it's correct! We can even fetch and read the data if we remove the header-only flag.

Now let's look at the `api.adoptium.net` by changing the FQDN and the vendor to `adoptium`.

```
$ curl -IX 'GET'   'https://api.adoptium.net/v3/assets/feature_releases/11/ga?architecture=x86&heap_size=normal&image_type=jre&jvm_impl=hotspot&os=windows&page=0&page_size=10&project=jdk&sort_method=DEFAULT&sort_order=DESC&vendor=adoptium'   -H 'accept: application/json'

HTTP/1.1 404 Not Found
Date: Wed, 08 Sep 2021 09:42:25 GMT
Content-Type: application/json
Connection: keep-alive
```

As we can see; it's not working! We get a `404` error which is somehow unexpected.

**Expected behavior**

I was expecting to get a `200` response with some information about available binaries. 

Stay safe and healthy!

**Comment by johnoliver** [comment]
You are requesting a windows/x86/jre, at the moment Adoptium has not released a binary that matches this, you can see our latest release at:

https://github.com/adoptium/temurin11-binaries/releases/jdk-11.0.12%2B7

We have a windows/x86/JDK, however no JRE. If you want that binary produced it would probably be a question for: https://github.com/adoptium/adoptium-support/issues but as far as I can tell the API is functioning correctly here.

Also note that Adoptium will not return AdoptOpenJDK binaries.

**Comment by funilrys** [comment]
Hi @johnoliver, 

Thanks for the feedback. Do we know a deprecation date for the `api.adoptopenjdk.net` endpoints ?

Thank you for the quick reaction!
