### ISSUE TITLE
what does migration to this api entail ?

### ISSUE THREAD

**Issue by maxandersen** [adoptium/api.adoptium.net#165]
**Is your feature request related to a problem? Please describe.**
https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/ says "Please migrate to using this new API as soon as possible" but no info what that means.

I assume it is change https://api.adoptopenjdk.net/ to https://api.adoptium.net/ but neither pages mention it. 

**Describe the solution you'd like**

A mention on https://api.adoptopenjdk.net/ that it is deprecated and  https://api.adoptium.net/ should be used instead.

And have  https://api.adoptium.net/ actually have overview, migration info and usage docs linked up as otherwise adoptopenjdk still looks the better option.

**Comment by maxandersen** [comment]
i'm trying to migrate jbang to use adoptium.net instead of adoptopenjdk but things are not working as expected:

-       private static final String JDK_DOWNLOAD_URL = "https://api.adoptopenjdk.net/v3/binary/latest/%d/ga/%s/%s/jdk/hotspot/normal/%s";
+       private static final String JDK_DOWNLOAD_URL = "https://api.adoptium.net/v3/binary/latest/%d/ga/%s/%s/jdk/hotspot/normal/%s";

I changed api.adoptopenjdk.net to api.adoptium.net and its definitely not working the same :)

I get empty responses on downloading what worked fine for api.adoptopenjdk.net.

some documentation of what migration is and what differences there are would be great.

Like, if adoptium wont include past builds like java 14 ? and wether adoptopenjdk will include future ones ?

At the moment at least I'm stuck on adoptopenjdk

**Comment by maxandersen** [comment]
example:
https://api.adoptium.net/v3/binary/latest/12/ga/mac/x64/jdk/hotspot/normal/adoptopenjdk gives 404
https://api.adoptopenjdk.net/v3/binary/latest/12/ga/mac/x64/jdk/hotspot/normal/adoptopenjdk works.

but I guess that is explained by:

"The same is not true in the other direction. We will not move the archived AdoptOpenJDK builds to Eclipse, since we wish to be clear that all releases available from Adoptium are both AQAvit and JCK tested, and have passed the enhanced Eclipse release process scrutiny."

that is quite unfortunate as that breaks jbang ability to download past java versions which is needed.

**Comment by maxandersen** [comment]
closing this as I wont need the migration as I need both version thus using api.foojay.io instead that wraps both adoptopenjdk and adoptium.

**Comment by karianna** [comment]
@johnoliver reopening in case there's a doc fix here

**Comment by karianna** [comment]
#199 should address the doc fixes
