### ISSUE TITLE
Need an endpoint for fetching the binary checksums

### ISSUE THREAD

**Issue by d3vel0per** [adoptium/api.adoptium.net#173]
**Is your feature request related to a problem? Please describe.**
While we do have endpoints that give us links for binary downloads I wasn't able to find anything the provides a checksum to verify against

**Describe the solution you'd like**
An endpoint that returns the checksum. Probably the same one that returns the binary but with an additional parameter that specifies the request is for a checksum

**Describe alternatives you've considered**
One alternative is to capture the redirect and append `.sha256.txt` at the end of the github url which happily returns the same but that isn't very user friendly

**Comment by tushev** [comment]
FYI there is a `checksum` field inside `package` or `installer` in https://api.adoptium.net/v3/assets/latest/17/hotspot?vendor=adoptium

What API endpoints are you using?

**Comment by d3vel0per** [comment]
Ok. Then that looks solved.
My apologies didnt check on this one.

I was using:

To fetch latest GA's
https://api.adoptium.net/v3/info/release_names?architecture=x64&heap_size=normal&image_type=jdk&os=windows&page=0&page_size=1&project=jdk&release_type=ga&sort_method=DEFAULT&sort_order=DESC&vendor=adoptium

And pick version string from the former to fetch binaries:
https://api.adoptium.net/v3/binary/version/jdk-17%2B35/windows/x64/jdk/hotspot/normal/adoptium?project=jdk

**Comment by d3vel0per** [comment]
I was expected some param on the second one to get the checksums but the other endpoint looks fine as well. Feel free to close this.
