### ISSUE TITLE
Invalid version string jdk8u302-b08.1 for LTS binaries

### ISSUE THREAD

**Issue by d3vel0per** [adoptium/api.adoptium.net#174]
**Describe the bug**
I was trying to fetch the set of LTS version strings and then fetch the respective binaries using the former. Works for everything else other than jdk8u302-b08.1

**To Reproduce**
```shell
$ curl -X 'GET' \
  'https://api.adoptium.net/v3/info/release_names?architecture=x64&heap_size=normal&image_type=jdk&lts=true&os=windows&page=0&page_size=3&project=jdk&release_type=ga&sort_method=DEFAULT&sort_order=DESC&vendor=adoptium' \
  -H 'accept: application/json'
{
  "releases": [
    "jdk-11.0.12+7",
    "jdk8u302-b08.1",
    "jdk8u302-b08"
  ]
}
```
and then try to fetch the binary for jdk8u302-b08.1:
```shell
$ curl -X 'GET' \
  'https://api.adoptium.net/v3/binary/version/jdk8u302-b08.1/linux/x64/jdk/hotspot/normal/adoptium?project=jdk' \
  -H 'accept: */*'
{"errorMessage":"No releases match the request"}
```

**Expected behavior**
Either redirect to a valid release or remove the listed version from the repository

**Comment by gdams** [comment]
@d3vel0per that `.1` release was a Windows re-spin only. Your first request asks for windows versions and then your second one tries to request a Linux binary.

**Comment by d3vel0per** [comment]
My bad, you are correct. I probably need to take a break ☕
