### ISSUE TITLE
Add 'source' API

### ISSUE THREAD

**Issue by jerboaa** [adoptium/api.adoptium.net#176]
**Is your feature request related to a problem? Please describe.**
There is a new feature in the build scripts which allows one to produce source tarball snapshots (`--create-source-archive` switch). This is similar to upstream's releases here:
https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/tag/jdk-11.0.13%2B6

For example `OpenJDK11U-sources_11.0.13_6_ea.tar.gz`. Yet, there is no good way via the API to be able to retrieve such a tarball. E.g. via a fictitious curl command such as:
```
$ curl -sL https://api.adoptium.net/v3/sources/latest/11/ga
```

**Describe the solution you'd like**
Define a new `sources` API which maps to downloading a source archive for a specific build.

**Comment by sxa** [comment]
Would you be ok with doing this only for production releases? i.e. not nightlies (as long as we're recording the shasums along with the nightlies it shouldn't be needed for those)

**Comment by jerboaa** [comment]
@sxa I'm not sure I follow. This is an issue for the API to retrieve a source archive. I.e. get the source archive once/if `--create-source-archive` gets promoted to default on or, say, added for *release* builds. Having said, that it would be OK as a developer could do a rebuild of the bits adding the switch so as to get a source archive as well. The sha alone isn't quite satisfying as one would then also have to a) know where the sources are to begin with (i.e. discover the repo/branch) b) then need to go the extra mile and clone themselves and be careful to not make any mistakes when trying to generate a source archive from it.

All things considered, I think the best option would be to turn it on by default and disable as needed. But that sounds like a decision to be made in the PMC :-)

**Comment by jerboaa** [comment]
Note that with https://github.com/adoptium/ci-jenkins-pipelines/pull/198 and https://github.com/adoptium/ci-jenkins-pipelines/pull/199 integrated there should be `-sources` tarballs in GH releases. Then those should be accessible via the API via the `v3/assets/latest` endpoint, which should be sufficient for an initial cut of https://github.com/adoptium/temurin-build/issues/2728

As such, I've reworded the enhancement request as it would be nice to get a source tarball redirect directly via the API too.

**Comment by johnoliver** [comment]
I have added the logic to detect and add source packages to adoptium repos, and they will be on the Release assets. In terms of adding a endpoint for pulling them. I am not sure exactly what would be correct here, is it a case we would want a 302 redirect to the source, or just return the source data?

**Comment by jerboaa** [comment]
The adoptium website uses these API calls (which also doesn't quite satisfy for a "get a source download redirect" feature):

```
$ curl -s 'https://api.adoptium.net/v3/assets/feature_releases/17/ga?vendor=eclipse' | jq '.[0] | .source'
{
  "link": "https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-sources_17.0.1_12.tar.gz",
  "name": "OpenJDK17U-sources_17.0.1_12.tar.gz",
  "size": 105458676
}
$ curl -s 'https://api.adoptium.net/v3/assets/feature_releases/11/ga?vendor=eclipse' | jq '.[0] | .source'
{
  "link": "https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.13%2B8/OpenJDK11U-sources_11.0.13_8.tar.gz",
  "name": "OpenJDK11U-sources_11.0.13_8.tar.gz",
  "size": 123491655
}
$ curl -s 'https://api.adoptium.net/v3/assets/feature_releases/8/ga?vendor=eclipse' | jq '.[0] | .source'
{
  "link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-sources_8u312b07.tar.gz",
  "name": "OpenJDK8U-sources_8u312b07.tar.gz",
  "size": 88460654
}
```

**Comment by karianna** [comment]
Closing this, the feature is there.  If there is a preferred redesign then we should raise a separate issue.
