### ISSUE TITLE
Swagger UI not available

### ISSUE THREAD

**Issue by caizixian** [adoptium/api.adoptium.net#177]
**Describe the bug**
The Swagger UI is not available as the response has 404 status code.

**To Reproduce**
1. Visit https://api.adoptium.net/swagger-ui as pointed by https://api.adoptium.net

**Expected behavior**
1. Displays Swagger UI for the API documentation

**Screenshots**
![Screen Shot 2021-09-27 at 15 47 40](https://user-images.githubusercontent.com/2891235/134851571-ffdbf29b-3d9d-40db-9cd4-83436c3b6490.png)

**Device (please complete the following information):**
 - OS: macOS 11.6
 - Browser: Chrome
 - Version: 93.0.4577.82

**Additional context**
N/A

**Comment by nickebbitt** [comment]
I was just about to report this, spotted the same.

**Comment by nickebbitt** [comment]
The link to the OpenAPI specs are also 404ing

https://api.adoptopenjdk.net/openapi

**Comment by nickebbitt** [comment]
just realised, that's the old adoptopenjdk site, I'll look to PR this repo with an update to the README

**Comment by nickebbitt** [comment]
I've found the swagger UI, it's actually hosted here:

https://api.adoptium.net/q/swagger-ui/

Maybe that was a change via a Quarkus upgrade that moved it?

**Comment by nickebbitt** [comment]
Opening the equivalent Open API URL redirects to the swagger UI

https://api.adoptium.net/q/openapi/

Using `curl` you get the Open API spec in `yaml` format e.g.

```
$ curl https://api.adoptium.net/q/openapi/

---
openapi: 3.0.3
info:
  title: v3
  description: ""
  version: 3.0.0
servers:
- url: https://api.adoptium.net
- url: https://staging-api.adoptium.net
tags:
- name: Assets
- name: Binary
- name: Installer
- name: Release Info
- name: Version
paths:
  /v3/assets/feature_releases/{feature_version}/{release_type}:
    get:
      tags:
      - Assets
      summary: Returns release information
      description: List of information about builds that match the current query
      operationId: searchReleases
      parameters:
      - name: feature_version
.
.
.
```

**Comment by nickebbitt** [comment]
I think we have a couple of options, fix references to point to the new location or override in the Quarkus smallrye config

e.g.
```
quarkus.smallrye-openapi.path=/swagger-ui
```

I'm unsure what dependencies exist against the Swagger API already so maintaining the existing structure feels safest - we should add also add a test though to ensure it doesn't move again without us realising.

Some info on how this works can be found here: https://quarkus.io/guides/openapi-swaggerui

**Comment by nickebbitt** [comment]
Just spotted there's also the following config option that should be considered
```
quarkus.swagger-ui.path=/swagger-ui
```

**Comment by tellison** [comment]
Good work, thanks Nick. Does look like an unintended config change. Best liaise with @johnoliver to agree on the right fixes.
