### ISSUE TITLE
Improve the API landing page experience

### ISSUE THREAD

**Issue by nickebbitt** [adoptium/api.adoptium.net#200]
**Is your feature request related to a problem? Please describe.**
The landing page you are presented with when you hit https://api.adoptium.net/ feels a little bland.

<img width="926" alt="Screenshot 2021-10-07 at 14 11 34" src="https://user-images.githubusercontent.com/5111725/136391345-1ba3e124-5a00-4c87-a790-b36ba0a7da5d.png">

**Describe the solution you'd like**
All the page offers is a link to the Swagger docs, maybe https://api.adoptium.net/ should just serve up the Swagger docs as per https://api.adoptium.net/q/swagger-ui/

**Describe alternatives you've considered**
Alternatively, if we want to keep the existing page, enhance the landing page to be a bit more informative. 

Possibly including links into the GitHub repo ("Fork me" style) for contributions would be nice.

**Comment by kushthedude** [comment]
Hi @karianna I am an outreachy applicant & would like to work on this issue, can you assign this to me?

**Comment by sakshi1215** [comment]
Hi @karianna I am an outreachy applicant, can I work on this issue?

**Comment by karianna** [comment]
@sakshi1215 Please go ahead!

**Comment by acoj202** [comment]
hello @karianna can i also work on this ,am also an outreachy applicant

**Comment by karianna** [comment]
@acoj202 please check with @sakshi1215 on Slack to see if you can work on it together.

**Comment by acoj202** [comment]
@sakshi1215 can we work on this project together

**Comment by sakshi1215** [comment]
@acoj202 I think its addressed in PR #500 @karianna is there anyhting more?

**Comment by karianna** [comment]
@johnoliver I think we need a new release

**Comment by sakshi1215** [comment]
> @johnoliver I think we need a new release

Is there a CD pipeline which updates the website or we need to just create a release tag?

**Comment by karianna** [comment]
John has to push manually from staging to live (we always have a Human in the loop as the API is critical)
