### ISSUE TITLE
NOTICE files in Swagger have breakages

### ISSUE THREAD

**Issue by karianna** [adoptium/api.adoptium.net#214]
Describe the bug
The two links in NOTICE don't work.

To Reproduce

Go to https://api.adoptopenjdk.net/q/swagger-ui/
Click on v3 issue tracker or https://api.adoptopenjdk.net/README links.
Expected behavior
Clicking on the links takes you to the relevant page. Instead it appears the target of the anchor tags has been incorrectly generated:
https://api.adoptopenjdk.net/%22https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/new/%22
https://api.adoptopenjdk.net/%22https://api.adoptopenjdk.net/README/%22

Screenshots
image

Inspecting the above in Edge:
image

Device (please complete the following information):

OS: Windows
Browser Edge
Version 94.0.992.31

**Comment by sxa** [comment]
> In that case we can close this.

@karianna I'm not sure I agree - we haven't migrated everyone across, and cannot for some use cases e.g. OpenJ9, AIX JDK16 for now), so for anyone still using the AdoptOpenJDK API the landing page on the site should redirect users to a valid issue tracker.
