### ISSUE TITLE
API /v3/info/release_versions doesn't contain enough information to construct a binary/installer request 

### ISSUE THREAD

**Issue by joerghall** [adoptium/api.adoptium.net#235]
The result of  /v3/info/release_versions  doesn't contains enough information to construct a download request.

Result:

```json
{
  "versions": [
    {
      "major": 0,
      "minor": 0,
      "security": 0,
      "patch": 0,
      "pre": "string",
      "adopt_build_number": 0,
      "semver": "11.0.0+28",
      "openjdk_version": "11.0.4+10-201907081820",
      "build": 0,
      "optional": "string"
    }
  ]
} 
```

Solution 1: Contain all attributes to create the Installer/Binary request

Solution 2: Include the url for installer / binary request

**Comment by johnoliver** [comment]
A typical download request would look like:

https://api.adoptium.net/v3/binary/latest/8/ga/linux/x64/jdk/hotspot/normal/eclipse

I don't think any of this would be needed from the `/v3/info/release_versions` endpoint. Can you give an example of a request you are trying to form that you do not have enough information for?

**Comment by sxa** [comment]
@joerghall Can you provide and example as mentioned by John in the previous comment please? If it's not providing an appropriate level of information we should definitely consider adding it :-)

**Comment by karianna** [comment]
Closing as stale.
