### ISSUE TITLE
Certificate has expired 

### ISSUE THREAD

**Issue by dmitry-shibanov** [adoptium/api.adoptium.net#240]
**Describe the bug**
Certificate has expired that is why we can not install java versions through the action. Sorry, If it's not right place to report. Could you please take a look on it, because it breaks all the builds using adoptium.

Could you please take a look on it, because it's critical for us.
**To Reproduce**
 - https://api.adoptium.net/
 - https://github.com/actions/setup-java/issues/248

**Expected behavior**  Update certificate.

**Screenshots**
![image](https://user-images.githubusercontent.com/28229110/141469651-9b28745f-0fe4-4e6f-bc15-4c89e0f2f7fc.png)
**Device (please complete the following information):**
 - OS: [e.g. Linux, MacOS, Windows, iOS, Android]

**Additional context**

**Comment by jonkoops** [comment]
I can confirm this is happening in our Github Actions as well.

**Comment by koenpunt** [comment]
Having a mirror of `api.adoptium.net` would've been very welcome right now. All our CI workflows are failing because of this.

**Comment by manusa** [comment]
Seems the certificate was just renewed :tada: 
![image](https://user-images.githubusercontent.com/488391/141475366-53d874dd-632d-4372-9d57-3dcab2d43775.png)
