### ISSUE TITLE
Create Schema for defining how vendors should advertise their JVMs to be included in the market place

### ISSUE THREAD

**Issue by johnoliver** [adoptium/api.adoptium.net#273]
Vendors need to publish information about the JVMs they are distributing, that need to be included in the marketplace API. In order to do this they need to make that data available in a well defined structured format that the market place API can consume. Define a schema for this data.

**Comment by tellison** [comment]
Am I correct in assuming that you envisage collecting, storing, and serving the marketplace data will be an extension of this existing API code (even if it is routed via it's own path/URL e.g. _api.adoptium.net/marketplace/_ or _api.marketplace.adoptium.net_)?

The alternative is to create a new repo for the marketplace logic, but we should avoid duplicating the code from here...

**Comment by johnoliver** [comment]
It would be a question open for debate. I think there are pros and cons either way here. I would say our options are:

### Option 1 - Keep both Adoptium V3 api and the marketplace api in the same repo
#### Pro
- Reduced duplication and hopefully effort
- Much of the build process is already set up

#### Con
Some of the current models are how Adopt(ium/openjdk) views the world, and they will have to remain backwards compatible (unless we bump to v4). It may be difficult over time to keep the Adoptium API backwards compatible while supporting other vendors use cases.

### Option 2 - Maintain totally separate repositories
#### Pro
- Allows for total flexibility for both Adoptium API and Marketplace
- Makes codebases more focused, less difficult to code review

#### Con
- Probably will end up with duplication

### Option 3 - Have separate repositories with a common core/library that both the marketplace and Adoptium API depends on.
#### Pro
- Less duplication

#### Con
- To some extent worst of both worlds, need to keep components compatible while also managing multiple repositories


I think my choice would be go with Option 1 for now. See if we can design models that are compatible with our own view, and other vendors. Ultimately if this proves not possible transition to 2 or 3. Regarding the deployment I would separate them by domain name rather than path, even though both domains may actually served by the same application in the current plan. This way if we ever do need to transition to a totally separate application we can shift it without impacting the existing Adoptium API.
