### ISSUE TITLE
Vendor "adoptium" is missing from swagger docs 

### ISSUE THREAD

**Issue by henrik242** [adoptium/api.adoptium.net#314]
I can use https://api.adoptium.net/v3/binary/latest/18/ea/alpine-linux/x64/jdk/hotspot/normal/adoptium to fetch the latest alpine-linux nightly, but it isn't possible to generate this URL using https://api.adoptium.net/q/swagger-ui/#/Binary/getBinary

The **vendor** menu only has `eclipse` in it, and it misses `adoptium`.

![Skjermbilde 2022-02-16 kl  12 06 17](https://user-images.githubusercontent.com/129931/154252087-f1b7eabf-2397-4ce6-877b-4c8e2b34339c.png)

See discussion at https://adoptium.slack.com/archives/C09NW3L2J/p1645009050578689?thread_ts=1645003789.204649&cid=C09NW3L2J

**Comment by johnoliver** [comment]
we chose eclipse as the vendor we should use, however allow adoptium for backwards compatibility as we did briefly have adoptium as the vendor in the api, however people should use eclipse, so we hide it in the docs
