### ISSUE TITLE
Latest Nightly builds no longer showing

### ISSUE THREAD

**Issue by gdams** [adoptium/api.adoptium.net#331]
Looking at https://api.adoptium.net/v3/assets/feature_releases/11/ea?heap_size=normal&image_type=jdk&page=0&page_size=10&project=jdk&sort_method=DEFAULT&sort_order=DESC&vendor=eclipse the latest release is from 21 days ago even though we are still pushing builds (most recent one was today https://github.com/adoptium/temurin11-binaries/releases/tag/jdk11u-2022-03-04-07-35-beta). Something seems to have gone wrong

**Comment by jerboaa** [comment]
Indeed. Note that no Linux x64 binaries seem to be here, though: https://github.com/adoptium/temurin11-binaries/releases/tag/jdk11u-2022-03-04-07-35-beta (others, for example aarch64 Linux is there): CTRL+F => `OpenJDK11u-jdk_x64_linux` turns up empty.

**Comment by gdams** [comment]
CC @johnoliver
