### ISSUE TITLE
No Checksum for AQAvit Results

### ISSUE THREAD

**Issue by gnu-andrew** [adoptium/api.adoptium.net#435]
There is no checksum for the AQAvit results in the JSON file, as there is for the binaries. This means that the results could potentially be replaced with different contents, while using the same filename.                                                                                          

Is this intentional? Or is there a plan to phase in something more like the package block for binaries, where the results have a name and checksum as well as the link?

**Comment by smlambert** [comment]
hi @gnu-andrew - @judovana beat you to raising an issue, please see https://github.com/adoptium/api.adoptium.net/issues/434 and there is a [discussion in the api channel](https://adoptium.slack.com/archives/CFUJV9XV0/p1653646312143329) in Slack, the conclusion of which I will add to issue 434.

Close this as dup 😄

**Comment by gnu-andrew** [comment]
Probably after I raised it in e-mail yesterday... :P
