### ISSUE TITLE
JDK17 EA downloads ambiguous response from /v3/binary/latest/17/ea/linux/aarch64/jdk/hotspot/normal/eclipse

### ISSUE THREAD

**Issue by Karm** [adoptium/api.adoptium.net#436]
Hello,

This URL used to work just fine for downloading the latest early access builds. It returns a selection of some JDK builds. I cannot see it documented on https://api.adoptium.net/q/swagger-ui/#/Binary/getBinary though.

## Reproducer

```
 curl -OJL 'https://api.adoptium.net/v3/binary/latest/17/ea/linux/x64/jdk/hotspot/normal/eclipse'
```
### Expected
Tarball is downloaded.

### Actual
The response is this text:
```
{"errorMessage":"Multiple binaries match request: 
[OpenJDK17U-jdk_x64_linux_hotspot_2022-05-27-19-32.tar.gz, 
OpenJDK17U-sbom_x64_linux_hotspot_2022-05-26-23-30.tar.gz]"}
```

Similar with `curl -OJL 'https://api.adoptium.net/v3/binary/latest/17/ea/linux/aarch64/jdk/hotspot/normal/eclipse'`.

**JDK 11** seems to download just fine.

Thx for hints.

**Comment by jerboaa** [comment]
/cc @johnoliver

Might be related to a new `sbom` artefact masking as `jdk` image?

**Comment by jerboaa** [comment]
Has this been deployed yet (I still see the issue)? I'm guessing this only will work again after the next nightly pipeline run?
