### ISSUE TITLE
mvnw clean install site -Padoptium fails in site reporting for api-v3-updater due to Quarkus code generation failure

### ISSUE THREAD

**Issue by karianna** [adoptium/api.adoptium.net#620]
Possibly a packaging / order of operations thing.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:53 min
[INFO] Finished at: 2023-07-05T14:22:19+12:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:4.0.0-M8:site (default-site) on project adoptium-api-v3-updater: Failed to get report for org.apache.maven.plugins:maven-dependency-plugin: Failed to execute goal io.quarkus:quarkus-maven-plugin:3.1.2.Final:generate-code (default) on project adoptium-api-v3-updater: Quarkus code generation phase has failed: /Users/martijnverburg/Documents/workspace/adoptium/api.adoptium.net/adoptium-updater-parent/adoptium-api-v3-updater/target/adoptium-api-v3-updater-3.0.1-SNAPSHOT.jar does not exist -> [Help 1]
[ERROR]

**Comment by gdams** [comment]
closing as fixed
