### ISSUE TITLE
v2 API is not working

### ISSUE THREAD

**Issue by mikeduminy** [adoptium/api.adoptium.net#681]
**Describe the bug**
The v2 API used by [njre](https://github.com/nvuillam/njre) is currently showing a heroku error page.

**To Reproduce**
1. Open https://api.adoptopenjdk.net/v2/info/releases/openjdk14?type=jre&openjdk_impl=hotspot&release=latest&os=linux&arch=x64&
2. Wait
3. See an error screen

![CleanShot 2023-09-11 at 15 16 24](https://github.com/adoptium/api.adoptium.net/assets/4092035/15707a84-0500-4156-a70b-9d5fb72debe8)

**Expected behavior**
A binary to be downloaded.

**Device (please complete the following information):**
 - OS: [e.g. Linux, MacOS, Windows, iOS, Android]
   - Mac and Linux, but probably all
   - Chrome and CURL, so probably all 
   - see URL

**Comment by karianna** [comment]
The AdoptOpenJDK v2 API is deprecated (defunct?) - @johnoliver to confirm.  Please do use the V3 API at api.adoptium.net

**Comment by gdams** [comment]
This is fixed now but as mentioned by Martijn, please migrate to the V3 API (api.adoptium.net)
