### ISSUE TITLE
Make SHA and GPG signatures easier to download

### ISSUE THREAD

**Issue by sxa** [adoptium/api.adoptium.net#853]
**Is your feature request related to a problem? Please describe.**
The blog post about using GPG signatures talks about pulling down the JSON information to retreive the direct link to an artifact. It would be a significant usability improvement if users could programatically use the API to download a sha sum or GPG signature file directly from the API instead of having yo go through that intermedaite step of pulling down the release information .While there is a small chance of the "latest" use case giving non-synchronised data at the exact point we upload a new release (and perhaps API caching/refreshing  makes this less likely?) I feel that the usability improvements we could get in the process documentation outweighs this

**Describe the solution you'd like**
An API call, documented via the swagger API, for retrieving the GPG and SHA artifacts for each file, to avoid having to expose the underlying github location to the user who wants to retrieve these.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by xavierfacq** [comment]
Hi Stewart,

Both endpoints are available in stagging and should be live next week. 

e.g. https://staging-api.adoptium.net/q/swagger-ui/#/Checksum/getChecksumByVersion

**Comment by xavierfacq** [comment]
It's live.
