### ISSUE TITLE
Mitigation for `invalidHostNameAllowed(true)` in MongoClient.kt

### ISSUE THREAD

**Issue by sxa** [adoptium/api.adoptium.net#861]
Discussed with @johnoliver

Ref: https://github.com/adoptium/api.adoptium.net/blob/52be774c47a374cd0cf13c40f2eb28f4b1158a16/adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/dataSources/persitence/mongo/MongoClient.kt#L67-L74

We should put something in place to avoid having to use `invalidHostNameAllowed(true)` in the code.

**Comment by sxa** [comment]
@johnoliver Are you able to put in a mitigation for this and test that it works?

**Comment by sxa** [comment]
ping @johnoliver Will you be able to take a look at this? It's one of the issues that was flagged in the external audit.

**Comment by johnoliver** [comment]
The fix for this has been merged, there is still a code path that includes `invalidHostNameAllowed` however is only used for testing
